name: 'Test Migration MS'
description: 'Queima Labs DevOps Stack - Test Migration - Docker-Compose File'
inputs:
  access_token:  # ID Service
    description: Personal Access Token - Scope read:pkg
    required: true
  service_port:  # ID Service
    description: Port where service is Exposed
    required: true
  config:
    description: JSON with all variables to configure job
    required: true
    default: "{\"NODE_ENV\":\"local\"}"
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}

runs:
  using: "composite"
  steps:  
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache Terraform
      uses: actions/cache@v2
      with:
        path: terraform/.terraform
        key: ${{ runner.os }}-terraform-v1-${{ hashFiles('**/service.tf') }}
        restore-keys: |
          ${{ runner.os }}-terraform-v1-

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1.2.1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Setup Credentials
      uses: queimadiaria/action-vault-aws@main
      with:
        vault_addr: ${{ secrets.VAULT_ADDR }}
        ssh_key: ${{ secrets.SSH_KEY }}
        awsqueima_environment: main

    - name: Setup Teraform environment
      run: |
        bash config/terraform.config.sh
        cat terraform/variables.auto.tfvars

    - name: Terraform Init
      working-directory: ./terraform
      run:  terraform init -upgrade
      
    - name: Terraform Validate
      working-directory: ./terraform
      run:  terraform validate

    - name: Terraform Format
      working-directory: ./terraform
      run:  terraform fmt -recursive

    - name: Terraform Plan
      id: plan
      if: github.event_name == 'pull_request'
      working-directory: ./terraform
      run: 'terraform plan -no-color || echo -e "################## \n Error at Terraform Plan \n ##################"'
      
    - name: Update Pull Request
      uses: actions/github-script@v4
      if: github.event_name == 'pull_request'
      env:
        PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
          #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
          #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
          <details><summary>Show Plan</summary>
          \`\`\`${process.env.PLAN}\`\`\`
          </details>
          *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

    - name: Terraform Plan Status
      if: steps.plan.outcome == 'failure'
      run: exit 1

    - name: Terraform Apply
      if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
      working-directory: ./terraform
      run: terraform apply -auto-approve
